spring.application.name=compusREST

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mysql}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Root.1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080