services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_serviciosocial
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_servicio_social
      - MYSQL_USER=user_social
      - MYSQL_PASSWORD=pass_social
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: